name: Overwatch Data Updater

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TZ: America/Los_Angeles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          wget -nc https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chrome-linux64.zip
          wget -nc https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chromedriver-linux64.zip
          unzip -o chrome-linux64.zip -d /home/runner/chrome-linux64
          unzip -o chromedriver-linux64.zip -d /home/runner/chromedriver-linux64

          pip install selenium
          pip install bs4

      - name: Set up TODAY env variable
        run: echo "TODAY=$(TZ='America/Los_Angeles' date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: List the files in /home/runner
        run: ls -alh /home/runner/chromedriver-linux64 /home/runner/chrome-linux64

      - name: Run scraper
        env:
          TODAY: ${{ env.TODAY }}
        run: python -u retriever.py
      
      - name: Commit and push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data/${{ env.TODAY }}_hero_data.csv

          git commit -m "Add hero data for ${{ env.TODAY }}"

          git push origin main
